repos:
  - repo: local
    hooks:
      - id: dart-format
        name: Dart format
        entry: dart format --set-exit-if-changed .
        language: system
        files: \.dart$
        stages: [pre-commit]

      - id: dart-analyze
        name: Flutter analyze
        entry: flutter analyze
        language: system
        stages: [pre-commit]
