// lib/models/location_model.dart
import 'package:hive_ce/hive.dart';

part 'location_model.g.dart'; // Will be generated by build_runner for Hive

@HiveType(typeId: 0) // typeId must be unique for each HiveObject
class Location extends HiveObject {
  @HiveField(0)
  final String id; // Unique ID for the location

  @HiveField(1)
  String name;

  @HiveField(3)
  String? description;

  @HiveField(4)
  String? address;

  @HiveField(5)
  List<String>? imageGuids;

  Location({
    required this.id,
    required this.name,
    this.description,
    this.address,
    List<String>? imageGuids,
  }) : imageGuids = imageGuids ?? [];

  Location copyWith({
    String? id,
    String? name,
    String? description,
    String? address,
    List<String>? imageGuids,
  }) {
    return Location(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      address: address ?? this.address,
      imageGuids: imageGuids != null
          ? List<String>.from(imageGuids)
          : (this.imageGuids != null
                ? List<String>.from(this.imageGuids!)
                : []),
    );
  }
}
