# .github/workflows/flutter_ci.yaml

name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.1
          cache: true

      - name: Cache build_runner
        uses: actions/cache@v4
        with:
          path: .dart_tool/build
          key: ${{ runner.os }}-build-${{ steps.flutter.outputs.VERSION }}-${{ hashFiles('pubspec.lock','build.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ steps.flutter.outputs.VERSION }}-

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run analyzer
        run: flutter analyze

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.1
          cache: true

      # Needed so the package: include in analysis_options.yaml resolves
      - name: Install dependencies (read-only; uses cache)
        run: flutter pub get --offline || flutter pub get

      # No pub get needed for formatting
      - name: Check Dart format
        run: dart format --output=none --set-exit-if-changed .

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [analyze, format]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.1
          cache: true

      - name: Cache build_runner
        uses: actions/cache@v4
        with:
          path: .dart_tool/build
          key: ${{ runner.os }}-build-${{ steps.flutter.outputs.VERSION }}-${{ hashFiles('pubspec.lock','build.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ steps.flutter.outputs.VERSION }}-

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test --coverage -j 2

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
